### ISSUE TITLE
Cannoot find dinput8 and scripts files anywhere.

### ISSUE THREAD

**Issue by mattdhinrichs** [ExOptsTeam/NFSU2ExOpts#22]
Downloaded one folder which had a link to download another folder and here are the entries. 

includes
NFSU2 Extra Options
.git.ignore
LICENSE
NFUS2ExtraOptionsSettings.ini
READ ME

**Comment by ThatD07** [comment]
You downloaded the source code and not the mod itself
https://github.com/ExOptsTeam/NFSU2ExOpts/releases

**Comment by mattdhinrichs** [comment]
HOLY HELL thank you so much
