### ISSUE TITLE
can this be used with NFSUnderground2.WidescreenFix and NFSU2HDReflections?

### ISSUE THREAD

**Issue by QUAKEULUS** [ExOptsTeam/NFSU2ExOpts#26]
or only one mod a time? they all overwrite each other's dinput8.dll, is it the same file for all 3?

**Comment by ThatD07** [comment]
you can use all 3 at the same time, dinput8.dll is basically the mod loader
you can get the latest version of it from here https://github.com/ThirteenAG/Ultimate-ASI-Loader/releases

**Comment by QUAKEULUS** [comment]
thanks!
