### ISSUE TITLE
A little upset, Gen:Variant.Razy detected.

### ISSUE THREAD

**Issue by TheReaper501** [ExOptsTeam/NFSU2ExOpts#5]
We all know what a Razy is. This mod is great, so please, take your razy out of it.

Kind regards,
Reaper

**Comment by DiamondMaster07** [comment]
That is a false alarm from your AV. ExOpts does not contain viruses. Add it to your antivirus exceptions

**Comment by TheReaper501** [comment]
hmm, I hope so. I can't afford taking any risk.

**Comment by nlgzrgn** [comment]
Extra Options edits your game memory to do its stuff. As you can see, the source code is totally open. If I included something else, you would see it easily in there.

As it edits memory, some AVs may detect it, but it's a false-positive. Just add an exception for the .asi file you downloaded; or for your whole game installation.

You are completely safe. :)

**Comment by TheReaper501** [comment]
Thanks for clarification. Great job with the mod though. :)
